name: Node.js App Setup
description: Sets up Node.js, installs dependencies, and prepares the environment.

inputs:
  working-directory:
    description: The directory where commands should be executed.
    required: true
    default: ./
  node-version:
    description: Node.js version to use.
    required: true
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install Dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
